---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: node-untaint
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-untaint
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["GET", "PATCH"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-untaint
roleRef:
  kind: ClusterRole
  name: node-untaint
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: node-untaint
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-node-untaint
  namespace: kube-system
  labels:
    app.kubernetes.io/name: spot-node-untaint
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spot-node-untaint
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spot-node-untaint
    spec:
      serviceAccountName: node-untaint
      containers:
      - name: node-untaint
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: bitnami/kubectl
        command: ["/bin/sh"]
        args: ["-c", "kubectl taint node $NODE_NAME kubernetes.azure.com/scalesetpriority-; sleep inf"]
      nodeSelector:
        kubernetes.azure.com/scalesetpriority: "spot"
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
